name: Build Windows EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4  # Обновлённая версия
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Build EXE
        run: pyinstaller --onefile class_off.py  # Путь относительно корня репозитория
      - name: Debug files
        run: ls -R
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: class_off.exe
          path: dist/class_off.exe
